### ISSUE TITLE
Document not opened in the right order 

### ISSUE THREAD

**Issue by AmosJack** [rmraya/Swordfish#1]
Hi, once i open an IDML document, the document doesn't open in the right order, for example, it start picking from day 29, then pick some text from day 30 etc. the right format ought to be from day 1 to day 2 to ... till day 31st

**Comment by rmraya** [comment]
Hi,

Text is extracted in the order in which it appears in the IDML file. The order in which authors enter text in InDesign is not always the order you see in a final page.

Send the IDML file to tech@maxprograms.com and I'll check if there is anything that can be done to improve text extraction.

Regards,
Rodolfo

**Comment by rmraya** [comment]
This issue should be reported for OpenXLIFF Filters. Closing here, noted for OpenXLIFF
