### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by ccremer** [rmraya/Swordfish#15]
Hi.
I've installed swordfish on Ubuntu and it was installed in `/opt/Maxprograms/Swordfish`.

How do I uninstall it? I've deleted the /opt/Maxprograms/Swordfish directory, but every now and then, I get a OS notification saying that it couldn't launch Swordfish due to missing binary. But I don't know what is trying to launch it, since I only ever started the app from terminal.

Can you help? Are there more files to delete?
I looked at the sources to figure out how the app gets installed, but it seems this repo doesn't contain any packaging/installer-related files.

**Comment by rmraya** [comment]
If you installed from source code, there is nothing else to remove.

**Comment by ccremer** [comment]
I did _not_ install from source code, I installed from the download page on your website.

**Comment by ccremer** [comment]
Hi. Can we please reopen this issue? This is not resolved.

**Comment by rmraya** [comment]
Since the problem you are experiencing is not related to the code in this repository, the issue will remain closed.

**Comment by ccremer** [comment]
Fine, but can you at least help me in uninstalling the software by pointing into the right direction? Is there another repository where I can place the issue? Some documentation? I don't believe I'm asking for much.
