### ISSUE TITLE
exported document truncates extreme amount of necessary untranslated texts

### ISSUE THREAD

**Issue by handhikadj** [rmraya/Swordfish#5]
![image](https://user-images.githubusercontent.com/22522638/108616500-68ce1f80-7440-11eb-8bf2-93ebf62da945.png)

the original document is on the left and the exported one is on the right

Kindly have it a look closer. 
You should notice extreme amount of texts are cut from the "Researchers around the world...." paragraph on the exported document.
Turns out it doesn't happen only on that paragraph, it happens on other paragraphs too

**Comment by jonury** [comment]
Hi,

I think your problem may be tags.
My experience is based on Swordfish 3, but I presume SF4 works the same way.
As I understand it, tags are what is left after Swordfish separates the document structure (skeleton) from the translatable material. 
Often, they are just format instructions (e.g. bold, superscript,…, as in the case of tags <<2>> and <<3>> in my example below) but sometimes they represent an important link between the skeleton and the text. These are what I call “structural tags” — they are tags that come at the very beginning or the very end of a segments (with absolutely nothing before/after, not even spaces).

Here’s an example:
https://www.evernote.com/shard/s124/sh/8fc2db1b-0c6e-4dfc-9bb3-2aebfc04bf02/9a24c07b47a2cc4ec35326395d7385fa


Notice that tag <<1>>  is right at the beginning. The translator put it at the very end. The result was that the entire sentence disappeared when exporting back to original document format. 
As I understand it, putting the sentence before tag <<1>> essentially meant that it got processed into the document structure during the export process.
I have learned that tags like <<1>> need to be put in exactly the same place as in the original.
Hope this helps.

John

**Comment by handhikadj** [comment]
thank you for responding.
don't get me wrong, but that is too technical what you've put out.
we're talking about the final exported document in user perspective, not developer perspective.
no matter what one might say, the paragraph I've told above should be preserved

**Comment by jonury** [comment]
Hi,
I'm just a user, not a developer. 
My reply was not excessively "technical". If I have diagnosed your problem correctly, you need to put the tags in exactly the same places when you translate. If one or more tags come at the very beginning of a segment, you have to put them there in your translation. The same if they come at the very end.
Look at this picture of the same sentence as before, but this time the problem is gone:
https://www.evernote.com/shard/s124/sh/dd9266ae-eec2-4ff8-b49b-3ce977900664/36efd00252d5c96325fc308a4b1b7954
This is the configuration of tags that gave the correct text in the end. So tag <<1>> is now at the very beginning. Putting it at the end was what resulted in the entire sentence disappearing.

**Comment by rmraya** [comment]
This looks like bad tag handling during translation. The only way to be sure is looking at the translated XLIFF file. 

Pictures of original and translated document are not enough, as they don't show how the translation was done.

**Comment by handhikadj** [comment]
> Hi,
> I'm just a user, not a developer.
> My reply was not excessively "technical". If I have diagnosed your problem correctly, you need to put the tags in exactly the same places when you translate. If one or more tags come at the very beginning of a segment, you have to put them there in your translation. The same if they come at the very end.
> Look at this picture of the same sentence as before, but this time the problem is gone:
> https://www.evernote.com/shard/s124/sh/dd9266ae-eec2-4ff8-b49b-3ce977900664/36efd00252d5c96325fc308a4b1b7954
> This is the configuration of tags that gave the correct text in the end. So tag <<1>> is now at the very beginning. Putting it at the end was what resulted in the entire sentence disappearing.

![image](https://user-images.githubusercontent.com/22522638/108621740-08060d80-7467-11eb-9682-642f0421e09c.png)

what's wrong with this then?

**Comment by rmraya** [comment]
This is not the right place for asking help on how to use Swordfish. You have two support options:

- Subscribe to the support group at  https://groups.io/g/maxprograms/ and ask for help there from other Swordfish users. 
- Get a Swordfish subscription and ask for help by email to tech@maxprograms.com . Your XLIFF file will be examined and you will get a solution to your problem.

Use GitHub issues only for reporting problems with the source code only.
