### ISSUE TITLE
Despite ANT_HOME, JAVA_HOME set, and added to PATH, the build fails at line 45

### ISSUE THREAD

**Issue by githubber** [rmraya/Swordfish#6]
I am wondering if it has to do with the way java.home has been named?
I'm just using Powershell with admin privs to run the commands, no Eclipse or anything.
The Swordfish directory was cloned to C:\
Ant is also in C:\
Java is installed where the AdoptOpenJDK installer put it (C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot)

Here is the error message:

`compile:
[delete] Deleting: C:\Swordfish\jars\swordfish.jar
[javac] Compiling 36 source files to C:\Swordfish\out
[jar] Building jar: C:\Swordfish\jars\swordfish.jar

link:

BUILD FAILED
C:\Swordfish\build.xml:45: Problem: failed to create task or type link
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any / declarations have taken place.

Total time: 4 seconds`

I've looked high and low, but nothing has helped.

**Comment by githubber** [comment]
Well, I decided to install Eclipse, set it up, and ran the project (just the ant portion). What do you know, it worked! npm install had some little problem, but `npm start` worked fine, and voila, I have Swordfish running on my Windows 10 MBPr.

Here is the result from running ant from within Eclipse:

Buildfile: C:\Swordfish\build.xml
distclean:
clean:
   [delete] Deleting directory C:\Swordfish\out
init:
    [mkdir] Created dir: C:\Swordfish\out
     [copy] Copying 4 files to C:\Swordfish\out
compile:
   [delete] Deleting: C:\Swordfish\jars\swordfish.jar
    [javac] Compiling 36 source files to C:\Swordfish\out
      [jar] Building jar: C:\Swordfish\jars\swordfish.jar
link:
     [link] Created C:\Swordfish\dist
   [delete] Deleting: C:\Swordfish\dist\lib\jrt-fs.jar
copyWindows:
     [move] Moving 55 files to C:\Swordfish\bin
     [move] Moving 10 files to C:\Swordfish\conf
     [move] Moving 5 files to C:\Swordfish\include
     [move] Moving 34 files to C:\Swordfish\legal
     [move] Moving 12 files to C:\Swordfish\lib
     [move] Moving 1 file to C:\Swordfish
   [delete] Deleting directory C:\Swordfish\dist
   [delete] Deleting: C:\Swordfish\jars\swordfish.jar
     [copy] Copying 1 file to C:\Swordfish\lib
copyUnix:
dist:
BUILD SUCCESSFUL
Total time: 8 seconds

**Comment by rmraya** [comment]
You probably have a PATH configuration issue. 

I use Visual Studio Code for development and a standard Windows Terminal (no privileges) for building Swordfish on Windows 10.

Glad to know you finally built Swordfish using Eclipse. That means that the ant build script is fine.
