### ISSUE TITLE
Refresh/update the source file

### ISSUE THREAD

**Issue by flolbr** [rmraya/Swordfish#7]
Hi,

I'm translating .idml files exported by Adobe InDesign and sometimes need to update the original document.
Is there any way to tell Swordfish to reload the original document to update the segments ? Currently I'm saving my translations to a memory that I re-apply to a new import of the project file, but that requires me to validate all the segments every time.

Thanks

**Comment by rmraya** [comment]
Users with a subscription can ask this kind of questions to tech@maxprograms.com
