### ISSUE TITLE
Tags in target are mishandled if they are not present in source

### ISSUE THREAD

**Issue by msoutopico** [rmraya/Swordfish#8]
### Preconditions

XLIFF file (attached) containing tags in target that are not present in source (line breaks added for readability):

```xml
<trans-unit resname="PQ_10_es" id="33301">
  <source><ph id="0">&lt;p&gt;</ph>For each of the areas listed below, please indicate the extent to which
    <ph id="1">&lt;u&gt;</ph>you currently need<ph id="2">&lt;/u&gt;</ph> professional learning activities.
    <ph id="3">&lt;/p&gt;</ph></source>
  <target><ph id="0">&lt;p&gt;</ph>Indique en qué medida 
    <ph id="4">&lt;span style='text-decoration: underline;'&gt;</ph>necesita<ph id="5">&lt;/span&gt;</ph> 
    actualmente aprendizaje profesional 
    <ph id="6">&lt;span style='text-decoration: underline;'&gt;</ph>pesonalizado<ph id="7">&lt;/span&gt;</ph> 
    en las siguientes áreas.<ph id="3">&lt;/p&gt;</ph></target>
</trans-unit>
```
### Steps to reproduce

1. Open XLIFF file in Swordfish
2. Edit the translation (without touching tags) and confirm the segment.
3. Projects > Export translations

### Expected results

1. The editor shows 4 tags in the source text, i.e. [1 [2-3] 4] and 6 tags in the target text, i.e. [1 [5-6] [7-8] 4]
2. The text changes, the tags are unaltered
3. Placeholders in the output XLIFF file are the same as in the input XLIFF file.

### Actual results

1. As expected in source. The editor shows 6 tags in the target text but these are [1 [2-3] [4-1] 2]
![](https://imgur.com/yNlctME.png)

2. As expected.
3. Placeholders in the output XLIFF file are mishandled:
    - placeholders `<ph id="4">&lt;span style='text-decoration: underline;'&gt;</ph>` and `<ph id="5">&lt;/span&gt;</ph>` are replaced with `<ph id="1">&lt;u&gt;</ph>` and `<ph id="2">&lt;/u&gt;</ph>`
    - placeholder `<ph id="6">&lt;span style='text-decoration: underline;'&gt;</ph>` is replaced with `<ph id="3">&lt;/p&gt;</ph>`
    - placeholder `<ph id="7">&lt;/span&gt;</ph>` is removed
    - placeholder `<ph id="3">&lt;/p&gt;</ph>` is removed

The target XLIFF looks like this:
```xml
<trans-unit resname="PQ_10_es" approved="yes" id="33301">
  <source><ph id="0">&lt;p&gt;</ph>For each of the areas listed below, please indicate the extent to which 
    <ph id="1">&lt;u&gt;</ph>you currently need<ph id="2">&lt;/u&gt;</ph> professional learning activities.
    <ph id="3">&lt;/p&gt;</ph></source>
  <target><ph id="0">&lt;p&gt;</ph>Indique en qué medida 
    <ph id="1">&lt;u&gt;</ph>necesita<ph id="2">&lt;/u&gt;</ph> 
    actualmente aprendizaje profesional 
    <ph id="3">&lt;/p&gt;</ph>personalizado en las siguientes áreas.</target>
</trans-unit>
```

### Files

[xliff.zip](https://github.com/rmraya/Swordfish/files/11367218/xliff.zip)

### Further info

When hovering over tags in the target text, the tooltips show the following:

| Tag | Placeholder                   | Ok? | Comment |
|-----|-------------------------------|-----|--------|
| 1   | `<ph id="0">&lt;p&gt;</ph>`     | y   | |
| 2   | `<ph id="1">&lt;u&gt;</ph>`     | ?   | Takes placeholder from source |
| 3   | `<ph id="2">&lt;/u&gt;</ph>`    | ?   | Takes placeholder from source |
| 4   | `<ph id="3">&lt;/p&gt;</ph>`    | N   | Takes placeholder from source |
| 1   | `<ph id="7">&lt;/span&gt;</ph>` | ?   | Shows placeholder in target but is removed in output |
| 2   | `<ph id="3">&lt;/p&gt;</ph>`    | y   | Shows same placeholder as tag 4 and is removed in output |

**Comment by msoutopico** [comment]
Another example, segment ID 34566:

Source XLIFF file has: 

```xml
<trans-unit resname="CL_PQ_es" id="34566">
  <source><ph id="0">&lt;p&gt;</ph>Principal Cover Letter for Online Administration<ph id="1">&lt;/p&gt;</ph></source>
  <target><ph id="0">&lt;p&gt;</ph>Formulario de admisión al cuestionario de gestión<ph id="2">&lt;br&gt;</ph>Recogida de datos online<ph id="1">&lt;/p&gt;</ph></target>
</trans-unit>
```

After making an edit in the text, confirming the segment and exporting translations, the target XLIFF looks like this: 

```xml
<trans-unit resname="CL_PQ_es" approved="yes" id="34566">
  <source><ph id="0">&lt;p&gt;</ph>Principal Cover Letter for Online Administration<ph id="1">&lt;/p&gt;</ph></source>
  <target><ph id="0">&lt;p&gt;</ph>Formulario de admisión al cuestionario de gestión<ph id="1">&lt;/p&gt;</ph>Recogida de datos en línea</target>
</trans-unit>
```

In other words, the placeholder `<ph id="2">&lt;br&gt;</ph>` is deleted (replaced with `<ph id="1">&lt;/p&gt;</ph>`)

Expected view in the editor: 

- source: [1-2]
- target: [1 [3] 2]

The editor actually displays: 

- source: [1-2]
- target: [1 [2] 1]

![](https://imgur.com/JgPcwkX.png)

When hovering over tags 2 and second 1, the tooltip shows `<ph id="1">&lt;/p&gt;</ph>` in both cases.

**Comment by rmraya** [comment]
Works as designed.

**Comment by msoutopico** [comment]
Could you please provide a bit more detail? Is it expected according to the design that certain tags are removed? Thanks.
